apiVersion: v1
kind: Service
metadata:
  name: {{ include "ortelius-docs.name" . }}
  labels:
  {{- range $key, $val := .Values.keptnLabels }}
    {{ $key }}: {{ $val | quote }}
  {{- end }}
  annotations:
    backstage.io/kubernetes-id: ortelius-docs
spec:
  selector:
    app: {{ include "ortelius-docs.name" . }}
    tier: backend
  ports:
    - name: hugo
      protocol: TCP
      port: 80
      targetPort: 80
