{{- if .Values.service.serviceMonitor.enabled -}}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ printf "%s-%s-%s" .Values.keptnLabels.keptnService .Values.keptnLabels.keptnProject .Values.keptnLabels.keptnStage }}
  namespace: {{ .Release.Namespace }}
  labels:
  {{- range $key, $val := .Values.keptnLabels }}
    {{ $key }}: {{ $val | quote }}
  {{- end }}
  annotations:
    backstage.io/kubernetes-id: ortelius-docs
spec:
  endpoints:
  - interval: 30s
    port: metrics
  namespaceSelector:
    matchNames:
    - {{ .Release.Namespace }}
  selector:
    matchLabels:
      app: {{ include "ortelius-docs.name" . }}
{{- end -}}