replicaCount: 1

image:
  repository: quay.io/ortelius/ortelius-docs
  tag: 10.0.0
  sha: a325ab3b18da  
  pullPolicy: Always

keptnLabels:
  keptnProject: ortelius
  keptnService: docs
  keptnStage: prd
