replicaCount: 1

image:
  repository: quay.io/ortelius/ortelius-docs
  tag: 10.0.0
  sha: a325ab3b18da  
  pullPolicy: Always

keptnLabels:
  keptnProject: ortelius
  keptnService: docs
  keptnStage: prd

service:
  serviceMonitor:
    enabled: false

ingress:
  enabled: false
  host: docs.ortelius.io
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/backend-protocol: HTTP
    nginx.ingress.kubernetes.io/ssl-passthrough: "false"
    backstage.io/kubernetes-id: ortelius-www
